# Generated by Django 4.1.4 on 2022-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'get_latest_by': 'updated_at'},
        ),
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
