# Generated by Django 4.1.4 on 2022-12-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_basicinfo_options_experience_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commonimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='commonimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='commonimage',
            name='updated_at',
        ),
    ]
