# Generated by Django 4.1.4 on 2022-12-21 14:01

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('profile', models.ImageField(upload_to=utils.get_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
