# Generated by Django 4.1.4 on 2022-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_basicinfo_order_alter_blog_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
