# Generated by Django 4.1.4 on 2022-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_review_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
