# Generated by Django 4.1.4 on 2022-12-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='logo',
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.commonimage'),
        ),
    ]
