# Generated by Django 4.1.4 on 2022-12-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_techskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20, null=True)),
                ('device_type', models.CharField(max_length=255, null=True)),
                ('device_name', models.CharField(max_length=255, null=True)),
                ('os', models.CharField(max_length=255, null=True)),
                ('browser', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='techskill',
            options={'ordering': ('order',)},
        ),
    ]
