# Generated by Django 4.1.4 on 2022-12-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_log_alter_blog_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='login_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
