# Generated by Django 4.1.4 on 2022-12-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
