# Generated by Django 4.1.4 on 2023-01-09 06:47

import django.core.validators
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_alter_blog_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2000), utils.max_value_current_year]),
        ),
    ]
