# Generated by Django 4.1.4 on 2023-01-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_demo_alter_certificate_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
