# Generated by Django 4.1.4 on 2023-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_demo_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='icon',
            field=models.CharField(help_text='<a target="_blank" href="https://fontawesome.com/v5/search?o=r&m=free">Fontawesome Icons 5.15.3</a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(help_text='<a target="_blank" href="https://fontawesome.com/v5/search?o=r&m=free">Fontawesome Icons 5.15.3</a>', max_length=50),
        ),
    ]
